### PR TITLE
Fix Zeitwerk compatibility issue

### PR DESCRIPTION
**Pull request by em-cd**
In a new Rails 7 app, adding the `mail-notify` gem to the Gemfile and running `rails zeitwerk:check` results in the following error:

```bash
rails aborted!
NameError: uninitialized constant ApplicationHelper
```

I spotted that there’s some work happening to [upgrade `mail-notify` to Rails 7](https://github.com/dxw/mail-notify/pull/53), but when I tried pointing the gem to use that branch, the error was still there. There is no such error in the dummy app when it's configured to use Zeitwerk mode, but I imagine that is because the dummy app loads the gem differently (using `require` instead of Bundler).

In this PR I’ve fixed the error by moving the main `notify.rb` file so that it sits directly in the `lib` folder. Now everything seems to load correctly and Zeitwerk is happy.

### CODE REVIEW

**Review by dragon-dxw — APPROVED** [review]

**Comment by thomasleese** [comment]
Hello! :wave: While upgrading this Gem in our application, I spotted this PR and I'm not sure this is quite the right fix. It seems to me like this fix would mean Zeitwerk is unable to determine the location of the `Mail::Notify` module as it's moved from `lib/mail/notify.rb` (where the directory structure matches the module structure) to `lib/notify.rb` (where we'd expect the module to just be `Notify`).

This is the error I was getting with this version of the Gem when running `rails zeitwerk:check`:

```
❯ rails zeitwerk:check
rails aborted!
NameError: uninitialized constant Mail

      Object.const_get(camel_cased_word)
            ^^^^^^^^^^
```

I had to put in a fix in place which was to `require "notify"` explicitly, which I don't think should be necessary.

**Comment by tvararu** [comment]
Same as @thomasleese, 1.0.5 is breaking our tests which was unexpected given it's a point release: https://github.com/DFE-Digital/find-a-lost-trn/runs/8131612568?check_suite_focus=true#step:5:13

**Comment by pezholio** [comment]
@tvararu So sorry about this! (And everyone who's referenced this PR!) I'm hoping to carve out some time to fix this today

**Comment by pezholio** [comment]
This is now fixed in the latest version (`1.1.0`). Context is in #63 if you're interested 👍

**Pull request merged**
